USE [master]
GO
/****** Object:  Database [Golf]    Script Date: 01.06.2024 10:59:10 ******/
CREATE DATABASE [Golf]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Golf', FILENAME = N'/var/opt/mssql/data/Golf.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Golf_log', FILENAME = N'/var/opt/mssql/data/Golf_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Golf] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Golf].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Golf] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Golf] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Golf] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Golf] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Golf] SET ARITHABORT OFF 
GO
ALTER DATABASE [Golf] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Golf] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Golf] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Golf] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Golf] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Golf] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Golf] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Golf] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Golf] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Golf] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Golf] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Golf] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Golf] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Golf] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Golf] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Golf] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Golf] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Golf] SET RECOVERY FULL 
GO
ALTER DATABASE [Golf] SET  MULTI_USER 
GO
ALTER DATABASE [Golf] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Golf] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Golf] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Golf] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Golf] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Golf] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Golf', N'ON'
GO
ALTER DATABASE [Golf] SET QUERY_STORE = ON
GO
ALTER DATABASE [Golf] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Golf]
GO
/****** Object:  Table [dbo].[Payment_history]    Script Date: 01.06.2024 10:59:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Payment_history](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NULL,
	[CZK] [float] NULL,
	[credit] [int] NULL,
	[payment_number] [varchar](100) NULL,
	[date] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Place]    Script Date: 01.06.2024 10:59:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Place](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NULL,
	[adress] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reservation]    Script Date: 01.06.2024 10:59:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reservation](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NULL,
	[place_id] [int] NULL,
	[from] [datetime] NULL,
	[to] [datetime] NULL,
	[title] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Role]    Script Date: 01.06.2024 10:59:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Role](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Role] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 01.06.2024 10:59:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[roleId] [int] NULL,
	[first_name] [varchar](50) NULL,
	[last_name] [varchar](50) NULL,
	[email] [varchar](100) NULL,
	[password] [varchar](30) NULL,
	[adress] [varchar](100) NULL,
	[zip] [varchar](10) NULL,
	[city] [varchar](50) NULL,
	[credit] [int] NULL,
	[isverified] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Payment_history]  WITH CHECK ADD FOREIGN KEY([user_id])
REFERENCES [dbo].[User] ([id])
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD FOREIGN KEY([place_id])
REFERENCES [dbo].[Place] ([id])
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD FOREIGN KEY([user_id])
REFERENCES [dbo].[User] ([id])
GO
ALTER TABLE [dbo].[User]  WITH CHECK ADD FOREIGN KEY([roleId])
REFERENCES [dbo].[Role] ([id])
GO
USE [master]
GO
ALTER DATABASE [Golf] SET  READ_WRITE 
GO
